version: '3'

services:
  nginx:
    image: nginx:1.20
    volumes:
      - ./www:/home/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8012:80
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./www:/home/www
    working_dir: /home/www